-- MySQL Script generated by MySQL Workbench
-- qui 08 mai 2025 12:57:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ferramenta` (
  `Codigo` INT NULL,
  `Nome` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Disponibilidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `Codigo` INT NOT NULL,
  `Cargo` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Data_Nascimento` DATE NULL,
  `Rua` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Cidade` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emprestimo` (
  `Codigo` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Data_Retirada` DATE NULL,
  `Data_Devolucao` DATE NULL,
  `Codigo_Funcionario` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `idx_Emp_Funcionario` (`Codigo_Funcionario`),
  CONSTRAINT `fk_Emprestimo_Funcionario`
    FOREIGN KEY (`Codigo_Funcionario`)
    REFERENCES `mydb`.`Funcionario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Emprestimo_Ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emprestimo_Ferramenta` (
  `Codigo_Emprestimo` INT NOT NULL,
  `Codigo_Ferramenta` INT NOT NULL,
  PRIMARY KEY (`Codigo_Emprestimo`, `Codigo_Ferramenta`),
  INDEX `idx_EmpFerr_CodFerr`    (`Codigo_Ferramenta`),
  INDEX `idx_EmpFerr_CodEmprest`  (`Codigo_Emprestimo`),
  CONSTRAINT `fk_EmpFerr_Emprestimo`
    FOREIGN KEY (`Codigo_Emprestimo`)
    REFERENCES `mydb`.`Emprestimo` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmpFerr_Ferramenta`
    FOREIGN KEY (`Codigo_Ferramenta`)
    REFERENCES `mydb`.`Ferramenta` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `Codigo` INT NOT NULL,
  `Preco` DOUBLE NULL,
  `Data_Entrega` DATE NULL,
  `Funcionario_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  -- índice simplificado, sem ASC nem VISIBLE
  KEY `fk_Compra_Funcionario1_idx` (`Funcionario_Codigo`),
  CONSTRAINT `fk_Compra_Funcionario1`
    FOREIGN KEY (`Funcionario_Codigo`)
    REFERENCES `mydb`.`Funcionario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `Codigo` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Quantidade` INT NULL,
  `Preco` DOUBLE NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Compra_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra_Material` (
  `Compra_Codigo` INT NOT NULL,
  `Material_Codigo` INT NOT NULL,
  PRIMARY KEY (`Compra_Codigo`, `Material_Codigo`),
  -- índices simplificados
  KEY `fk_Compra_has_Material_Material1_idx` (`Material_Codigo`),
  KEY `fk_Compra_has_Material_Compra1_idx`  (`Compra_Codigo`),
  CONSTRAINT `fk_Compra_has_Material_Compra1`
    FOREIGN KEY (`Compra_Codigo`)
    REFERENCES `mydb`.`Compra` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_has_Material_Material1`
    FOREIGN KEY (`Material_Codigo`)
    REFERENCES `mydb`.`Material` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
